language: go

go:
  - 1.9.x
  - tip

before_install:
  - go get -t -v ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -race -coverprofile=models.coverprofile -covermode=atomic ./models
  - go test -race -coverprofile=main.coverprofile -covermode=atomic

after_success:
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci
